# Generated by Django 3.2.6 on 2021-12-29 23:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chat_app', '0001_initial'),
        ('youonline_social_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatparticipant',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chatparticipant_createdby', to='youonline_social_app.profile'),
        ),
        migrations.AddField(
            model_name='chatparticipant',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chatparticipant_profile', to='youonline_social_app.profile'),
        ),
        migrations.AddField(
            model_name='chatparticipant',
            name='removed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chatparticipant_removedby', to='youonline_social_app.profile'),
        ),
        migrations.AddField(
            model_name='chatmessagemedia',
            name='chat_message',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chatmessagemedia_chatmessage', to='chat_app.chatmessage'),
        ),
        migrations.AddField(
            model_name='chatmessagemedia',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chatmessagemedia_profile', to='youonline_social_app.profile'),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='chat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chatmessage_chat', to='chat_app.chat'),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chatmessage_profile', to='youonline_social_app.profile'),
        ),
        migrations.AddField(
            model_name='chatdeletiontracker',
            name='chat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chatdeletiontracker_chat', to='chat_app.chat'),
        ),
        migrations.AddField(
            model_name='chatdeletiontracker',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chatdeletiontracker_profile', to='youonline_social_app.profile'),
        ),
        migrations.AddField(
            model_name='chat',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chat_profile', to='youonline_social_app.profile'),
        ),
        migrations.AlterUniqueTogether(
            name='chatparticipant',
            unique_together={('profile', 'chat')},
        ),
    ]
