# Generated by Django 3.2.6 on 2022-01-12 07:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('youonline_social_app', '0003_auto_20220110_1717'),
        ('chat_app', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='last_message',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chat_lastmessage', to='chat_app.chatmessage'),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='deleted_by',
            field=models.ManyToManyField(related_name='chatmessage_deletedby', to='youonline_social_app.Profile'),
        ),
    ]
