# Generated by Django 3.2.6 on 2022-01-13 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youonline_social_app', '0003_auto_20220110_1717'),
        ('chat_app', '0003_auto_20220112_1233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmessage',
            name='deleted_by',
            field=models.ManyToManyField(blank=True, related_name='chatmessage_deletedby', to='youonline_social_app.Profile'),
        ),
    ]
