# Generated by Django 3.2.6 on 2022-01-25 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youonline_social_app', '0007_auto_20220125_1037'),
        ('chat_app', '0006_auto_20220117_1127'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='read_by',
            field=models.ManyToManyField(blank=True, related_name='chatmessage_readby', to='youonline_social_app.Profile'),
        ),
    ]
