# Generated by Django 3.2.6 on 2022-02-10 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_app', '0007_chatmessage_read_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessagemedia',
            name='is_compressed',
            field=models.BooleanField(default=False),
        ),
    ]
