# Generated by Django 3.2.6 on 2022-03-29 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_app', '0010_chatmessagemedia_bucket_uploaded'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='media_message',
            field=models.BooleanField(default=False),
        ),
    ]
