# Generated by Django 3.2.6 on 2022-05-13 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youonline_social_app', '0028_profilestory_except_friends'),
        ('chat_app', '0011_chatmessage_media_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='delivered_to',
            field=models.ManyToManyField(blank=True, related_name='chatmessage_delivered_to', to='youonline_social_app.Profile'),
        ),
    ]
