# Generated by Django 3.2.6 on 2022-05-20 11:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat_app', '0012_chatmessage_delivered_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='blocked_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='block_user_profile', to='youonline_social_app.profile'),
        ),
    ]
