# Generated by Django 3.2.6 on 2022-05-20 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_app', '0013_chat_blocked_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatparticipant',
            name='muted_till',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
