# Generated by Django 3.2.6 on 2021-12-29 23:26

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Automotive',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=64)),
                ('slug', models.SlugField(blank=True, max_length=255, null=True, unique=True)),
                ('street_adress', models.CharField(blank=True, max_length=255, null=True)),
                ('longitude', models.CharField(blank=True, max_length=255, null=True)),
                ('latitude', models.CharField(blank=True, max_length=255, null=True)),
                ('mobile', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('description', models.TextField(blank=True, null=True)),
                ('car_type', models.CharField(blank=True, choices=[('New', 'New'), ('Used', 'Used')], max_length=255, null=True)),
                ('quantity', models.BigIntegerField(blank=True, null=True)),
                ('kilometers', models.BigIntegerField(blank=True, null=True)),
                ('body_condition', models.CharField(blank=True, choices=[('Perfect Inside and Outside', 'Perfect Inside and Outside'), ('No accidents, very few faults', 'No accidents, very few faults'), ('Bit of wear tear, all repaired', 'Bit of wear tear, all repaired'), ('Lots of wear tear to the body', 'Lots of wear tear to the body')], max_length=255, null=True)),
                ('inside_out', models.CharField(blank=True, choices=[('Perfect Inside and Outside', 'Perfect Inside and Outside'), ('Minor faults, all fixed', 'Minor faults, all fixed'), ('Major faults fixed, small remains', 'Major faults fixed, small remains'), ('Ongoing minor major faults', 'Ongoing minor major faults')], max_length=255, null=True)),
                ('transmission_type', models.CharField(blank=True, choices=[('Manual Transmission', 'Manual Transmission'), ('Automatic Transmission', 'Automatic Transmission')], max_length=255, null=True)),
                ('specs', models.CharField(blank=True, choices=[('European Specs', 'European Specs'), ('GCC Specs', 'GCC Specs'), ('Japanese Specs', 'Japanese Specs'), ('North American Specs', 'North American Specs'), ('Other', 'Other')], max_length=255, null=True)),
                ('door', models.CharField(blank=True, choices=[('2 doors', '2 doors'), ('3 doors', '3 doors'), ('4 doors', '4 doors'), ('5+ doors', '5+ doors')], max_length=255, null=True)),
                ('power', models.CharField(blank=True, choices=[('Less than 150 HP', 'Less than 150 HP'), ('150- 200 HP', '150- 200 HP'), ('200- 300 HP', '200- 300 HP'), ('300- 400 HP', '300- 400 HP'), ('400- 500 HP', '400- 500 HP'), ('Other', 'Other')], max_length=255, null=True)),
                ('fuel_type', models.CharField(blank=True, choices=[('Gasoline', 'Gasoline'), ('Diesel', 'Diesel'), ('Hybrid', 'Hybrid'), ('Electric', 'Electric')], max_length=255, null=True)),
                ('year', models.CharField(blank=True, max_length=255, null=True)),
                ('color', models.CharField(blank=True, max_length=255, null=True)),
                ('warranty', models.BooleanField(default=False)),
                ('privacy', models.CharField(blank=True, choices=[('Public', 'Public'), ('OnlyMe', 'OnlyMe'), ('Friends', 'Friends')], max_length=255, null=True)),
                ('verification_status', models.CharField(blank=True, choices=[('Pending', 'Pending'), ('Verified', 'Verified'), ('Rejected', 'Rejected')], default='Pending', max_length=255, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('is_promoted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Automotive',
            },
        ),
        migrations.CreateModel(
            name='AutomotiveCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'AutomotiveCategory',
            },
        ),
        migrations.CreateModel(
            name='AutomotiveMake',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'AutomotiveMake',
            },
        ),
        migrations.CreateModel(
            name='AutomotiveMedia',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('automotive_image', models.ImageField(null=True, upload_to='automotive_images/%Y/%m')),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'AutomotiveMedia',
            },
        ),
        migrations.CreateModel(
            name='AutomotiveModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'AutomotiveModel',
            },
        ),
        migrations.CreateModel(
            name='AutomotiveSubCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'AutomotiveSubCategory',
            },
        ),
        migrations.CreateModel(
            name='AutomotiveSubSubCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'AutomotiveSubSubCategory',
            },
        ),
        migrations.CreateModel(
            name='ContactAutomotive',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=255, null=True)),
                ('message', models.TextField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'ContactAutomotive',
            },
        ),
        migrations.CreateModel(
            name='FavouriteAutomotive',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'FavouriteAutomotive',
            },
        ),
        migrations.CreateModel(
            name='ReportAutomotive',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=255, null=True)),
                ('message', models.TextField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('automotive', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='automotive_app.automotive')),
            ],
            options={
                'db_table': 'ReportAutomotive',
            },
        ),
    ]
