# Generated by Django 3.2.6 on 2022-01-03 07:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('youonline_social_app', '0001_initial'),
        ('automotive_app', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='automotivemedia',
            name='automotive_video',
            field=models.FileField(null=True, upload_to='automotive_video/%Y/%m'),
        ),
        migrations.AlterField(
            model_name='automotivemedia',
            name='automotive',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='automotivemedia_automotive', to='automotive_app.automotive'),
        ),
        migrations.AlterField(
            model_name='automotivemedia',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='automotivemedia_profile', to='youonline_social_app.profile'),
        ),
    ]
