# Generated by Django 3.2.6 on 2022-01-04 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automotive_app', '0004_automotivemake_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='automotivemake',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='automotive_make_images'),
        ),
    ]
