# Generated by Django 3.2.6 on 2022-01-05 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automotive_app', '0005_alter_automotivemake_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='automotivemedia',
            name='vid_thumbnail',
            field=models.FileField(null=True, upload_to='automotive_video/%Y/%m'),
        ),
    ]
