# Generated by Django 3.2.6 on 2022-01-07 12:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('youonline_social_app', '0001_initial'),
        ('job_app', '0003_currency_country'),
        ('automotive_app', '0006_automotivemedia_vid_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='automotive',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='automotive_category', to='automotive_app.automotivecategory'),
        ),
        migrations.AlterField(
            model_name='automotive',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='automotive_city', to='youonline_social_app.city'),
        ),
        migrations.AlterField(
            model_name='automotive',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='automotive_company', to='job_app.company'),
        ),
        migrations.AlterField(
            model_name='automotive',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='automotive_country', to='youonline_social_app.country'),
        ),
        migrations.AlterField(
            model_name='automotive',
            name='currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='automotive_currency', to='job_app.currency'),
        ),
        migrations.AlterField(
            model_name='automotive',
            name='language',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='automotive_language', to='youonline_social_app.language'),
        ),
        migrations.AlterField(
            model_name='automotive',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='automotive_profile', to='youonline_social_app.profile'),
        ),
        migrations.AlterField(
            model_name='automotive',
            name='state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='automotive_state', to='youonline_social_app.state'),
        ),
        migrations.AlterField(
            model_name='automotive',
            name='sub_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='automotive_subcategory', to='automotive_app.automotivesubcategory'),
        ),
        migrations.AlterField(
            model_name='automotive',
            name='sub_sub_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='automotive_subsubcategory', to='automotive_app.automotivesubsubcategory'),
        ),
        migrations.AlterField(
            model_name='contactautomotive',
            name='automotive',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contactautomotive_automotive', to='automotive_app.automotive'),
        ),
        migrations.AlterField(
            model_name='contactautomotive',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contactautomotive_profile', to='youonline_social_app.profile'),
        ),
        migrations.AlterField(
            model_name='favouriteautomotive',
            name='automotive',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='favouriteautomotive_automotive', to='automotive_app.automotive'),
        ),
        migrations.AlterField(
            model_name='favouriteautomotive',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='favouriteautomotive_profile', to='youonline_social_app.profile'),
        ),
        migrations.AlterField(
            model_name='reportautomotive',
            name='automotive',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reportautomotive_automotive', to='automotive_app.automotive'),
        ),
        migrations.AlterField(
            model_name='reportautomotive',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reportautomotive_profile', to='youonline_social_app.profile'),
        ),
    ]
