# Generated by Django 3.2.6 on 2022-01-14 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('youonline_social_app', '0003_auto_20220110_1717'),
        ('automotive_app', '0007_auto_20220107_1701'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='favouriteautomotive',
            unique_together={('profile', 'automotive')},
        ),
    ]
