# Generated by Django 3.2.6 on 2022-01-18 07:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('automotive_app', '0008_alter_favouriteautomotive_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='automotivemodel',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='automotive_app.automotivesubcategory'),
        ),
        migrations.AddField(
            model_name='automotivemodel',
            name='year',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
    ]
