# Generated by Django 3.2.6 on 2022-01-24 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automotive_app', '0010_auto_20220124_1642'),
    ]

    operations = [
        migrations.AlterField(
            model_name='automotivecategory',
            name='title',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='automotivemake',
            name='title',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='automotivemodel',
            name='title',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='automotivesubcategory',
            name='title',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='automotivesubsubcategory',
            name='title',
            field=models.CharField(max_length=64),
        ),
    ]
