# Generated by Django 3.2.6 on 2022-02-10 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automotive_app', '0011_auto_20220124_1727'),
    ]

    operations = [
        migrations.AddField(
            model_name='automotivemedia',
            name='is_compressed',
            field=models.BooleanField(default=False),
        ),
    ]
