# Generated by Django 3.2.6 on 2022-02-14 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automotive_app', '0013_automotivecomparison'),
    ]

    operations = [
        migrations.AddField(
            model_name='automotivecomparison',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
