# Generated by Django 3.2.6 on 2022-03-16 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automotive_app', '0014_automotivecomparison_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='automotivemedia',
            name='video_compressed',
            field=models.BooleanField(default=False),
        ),
    ]
