# Generated by Django 3.2.6 on 2022-03-17 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automotive_app', '0015_automotivemedia_video_compressed'),
    ]

    operations = [
        migrations.AddField(
            model_name='automotivemedia',
            name='bucket_uploaded',
            field=models.BooleanField(default=False),
        ),
    ]
