# Generated by Django 3.2.6 on 2022-03-23 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automotive_app', '0016_automotivemedia_bucket_uploaded'),
    ]

    operations = [
        migrations.AlterField(
            model_name='automotivemake',
            name='image',
            field=models.ImageField(blank=True, max_length=256, null=True, upload_to='automotive_make_images'),
        ),
        migrations.AlterField(
            model_name='automotivemedia',
            name='automotive_image',
            field=models.ImageField(max_length=256, null=True, upload_to='automotive_images/%Y/%m'),
        ),
        migrations.AlterField(
            model_name='automotivemedia',
            name='automotive_video',
            field=models.FileField(max_length=256, null=True, upload_to='automotive_video/%Y/%m'),
        ),
        migrations.AlterField(
            model_name='automotivemedia',
            name='vid_thumbnail',
            field=models.FileField(max_length=256, null=True, upload_to='automotive_video/%Y/%m'),
        ),
    ]
