# Generated by Django 3.2.6 on 2022-08-30 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automotive_app', '0017_auto_20220323_1502'),
    ]

    operations = [
        migrations.AddField(
            model_name='automotivemake',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
    ]
