# Generated by Django 3.2.6 on 2022-09-06 11:23

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('youonline_social_app', '0042_auto_20220730_1256'),
        ('automotive_app', '0019_auto_20220903_1234'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutomotiveSearchHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('autotomotive', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='automotivesearchhistory_autotomotive', to='automotive_app.automotive')),
                ('profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='automotivesearchhistory_profile', to='youonline_social_app.profile')),
            ],
            options={
                'db_table': 'AutomotiveSearchHistory',
            },
        ),
    ]
