# Generated by Django 3.2.6 on 2022-09-14 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automotive_app', '0021_auto_20220907_1221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='automotive',
            name='transmission_type',
            field=models.CharField(blank=True, choices=[('Manual', 'Manual'), ('Automatic', 'Automatic')], max_length=255, null=True),
        ),
    ]
