# Generated by Django 3.2.6 on 2022-09-26 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automotive_app', '0023_auto_20220921_1448'),
    ]

    operations = [
        migrations.AddField(
            model_name='automotive',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
