# Generated by Django 3.2.6 on 2022-09-27 05:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('automotive_app', '0024_automotive_is_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='automotivemake',
            old_name='category',
            new_name='sub_category',
        ),
    ]
