# Generated by Django 3.2.6 on 2022-09-28 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automotive_app', '0025_rename_category_automotivemake_sub_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='automotivemedia',
            name='automotive_image',
            field=models.ImageField(blank=True, max_length=256, null=True, upload_to='automotive_images/%Y/%m'),
        ),
        migrations.AlterField(
            model_name='automotivemedia',
            name='automotive_video',
            field=models.FileField(blank=True, max_length=256, null=True, upload_to='automotive_video/%Y/%m'),
        ),
        migrations.AlterField(
            model_name='automotivemedia',
            name='vid_thumbnail',
            field=models.FileField(blank=True, max_length=256, null=True, upload_to='automotive_video/%Y/%m'),
        ),
    ]
