# Generated by Django 3.2.6 on 2022-09-28 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automotive_app', '0026_auto_20220928_1056'),
    ]

    operations = [
        migrations.AddField(
            model_name='automotive',
            name='is_deal',
            field=models.BooleanField(default=False),
        ),
    ]
