# Generated by Django 3.2.6 on 2022-10-04 08:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('youonline_social_app', '0047_auto_20220928_1319'),
        ('automotive_app', '0028_automotiveview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='automotiveview',
            name='viewer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='automotiveview_viewer', to='youonline_social_app.profile'),
        ),
    ]
