# Generated by Django 3.2.6 on 2022-10-05 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automotive_app', '0029_alter_automotiveview_viewer'),
    ]

    operations = [
        migrations.AddField(
            model_name='automotivecategory',
            name='view_count',
            field=models.BigIntegerField(default=0),
        ),
    ]
