# Generated by Django 3.2.6 on 2022-10-05 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automotive_app', '0030_automotivecategory_view_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='automotive',
            name='view_count',
            field=models.BigIntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='AutomotiveView',
        ),
    ]
