# Generated by Django 3.2.6 on 2022-10-06 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('automotive_app', '0031_auto_20221005_1810'),
    ]

    operations = [
        migrations.RenameField(
            model_name='automotivesearchhistory',
            old_name='autotomotive',
            new_name='automotive',
        ),
    ]
