# Generated by Django 3.2.6 on 2022-10-10 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automotive_app', '0032_rename_autotomotive_automotivesearchhistory_automotive'),
    ]

    operations = [
        migrations.AlterField(
            model_name='automotive',
            name='fuel_type',
            field=models.CharField(blank=True, choices=[('Petrol', 'Petrol'), ('Diesel', 'Diesel'), ('LPG', 'LPG'), ('CNG', 'CNG'), ('Hybrid', 'Hybrid'), ('Electric', 'Electric')], max_length=255, null=True),
        ),
    ]
