# Generated by Django 3.2.6 on 2022-06-16 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_app', '0003_auto_20220614_1218'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmedia',
            name='image_compressed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='productmedia',
            name='image_thumbnail',
            field=models.ImageField(blank=True, max_length=512, null=True, upload_to='ProductImages'),
        ),
        migrations.AddField(
            model_name='productmedia',
            name='video_compressed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='productmedia',
            name='video_thumbnail',
            field=models.ImageField(blank=True, max_length=512, null=True, upload_to='ProductVideos'),
        ),
    ]
