# Generated by Django 3.2.6 on 2022-06-16 07:34

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('youonline_social_app', '0034_post_product_post'),
        ('ecommerce_app', '0004_auto_20220616_1049'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='publish_status',
            field=models.CharField(choices=[('Published', 'Published'), ('Draft', 'Draft'), ('Scheduled', 'Scheduled')], default='Published', max_length=32),
        ),
        migrations.CreateModel(
            name='ProductSchedule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('publish_time', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('is_published', models.BooleanField(default=False)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productschedule_product', to='ecommerce_app.product')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productschedule_profile', to='youonline_social_app.profile')),
            ],
            options={
                'verbose_name_plural': 'Product Schedules',
                'db_table': 'ProductSchedule',
            },
        ),
    ]
