# Generated by Django 3.2.6 on 2022-06-30 10:58

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_app', '0005_auto_20220616_1234'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchivedProduct',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='archivedproduct_product', to='ecommerce_app.product')),
            ],
            options={
                'verbose_name_plural': 'Archived Product',
                'db_table': 'ArchivedProduct',
            },
        ),
    ]
