# Generated by Django 3.2.6 on 2022-01-03 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classified_app', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='classifiedcategory',
            name='image',
            field=models.ImageField(null=True, upload_to='classified_category_images/%Y/%m'),
        ),
    ]
