# Generated by Django 3.2.6 on 2022-01-04 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classified_app', '0003_classifiedcategory_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classifiedcategory',
            name='image',
            field=models.ImageField(null=True, upload_to='classified_category_images'),
        ),
    ]
