# Generated by Django 3.2.6 on 2022-02-10 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classified_app', '0006_alter_favouriteclassified_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='classifiedmedia',
            name='is_compressed',
            field=models.BooleanField(default=False),
        ),
    ]
