# Generated by Django 3.2.6 on 2022-03-23 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classified_app', '0009_classifiedmedia_bucket_uploaded'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classifiedcategory',
            name='image',
            field=models.ImageField(max_length=255, null=True, upload_to='classified_category_images'),
        ),
        migrations.AlterField(
            model_name='classifiedmedia',
            name='classified_image',
            field=models.ImageField(max_length=256, null=True, upload_to='classified_images/%Y/%m'),
        ),
        migrations.AlterField(
            model_name='classifiedmedia',
            name='classified_video',
            field=models.FileField(max_length=256, null=True, upload_to='classified_video/%Y/%m'),
        ),
        migrations.AlterField(
            model_name='classifiedmedia',
            name='classified_video_thumbnail',
            field=models.FileField(max_length=256, null=True, upload_to='classified_video_thumbnail/%Y/%m'),
        ),
    ]
