# Generated by Django 3.2.6 on 2022-04-20 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classified_app', '0010_auto_20220323_1455'),
    ]

    operations = [
        migrations.AddField(
            model_name='classified',
            name='business_directory',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='classified',
            name='employees_count',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='classified',
            name='established_year',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='classified',
            name='manager_name',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='classifiedcategory',
            name='business_directory',
            field=models.BooleanField(default=False),
        ),
    ]
