# Generated by Django 3.2.6 on 2022-08-22 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classified_app', '0011_auto_20220420_1130'),
    ]

    operations = [
        migrations.AddField(
            model_name='classified',
            name='deal_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='classified',
            name='is_deal',
            field=models.BooleanField(default=False),
        ),
    ]
