# Generated by Django 3.2.6 on 2022-08-23 05:05

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('youonline_social_app', '0042_auto_20220730_1256'),
        ('classified_app', '0012_auto_20220822_1212'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassifiedSearchHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('classified', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='classifiedsearchhistory_classfied', to='classified_app.classified')),
                ('profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='classifiedsearchhistory_profile', to='youonline_social_app.profile')),
            ],
            options={
                'db_table': 'ClassifiedSearchHistory',
            },
        ),
    ]
