# Generated by Django 3.2.6 on 2022-08-30 06:05

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('classified_app', '0013_classifiedsearchhistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassifiedeMake',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=64)),
                ('image', models.ImageField(blank=True, max_length=256, null=True, upload_to='classified_make_images')),
                ('is_featured', models.BooleanField(default=False)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='classifiedmake_subcategory', to='classified_app.classifiedsubcategory')),
            ],
            options={
                'db_table': 'ClassifiedeMake',
            },
        ),
        migrations.AddField(
            model_name='classified',
            name='make',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='classified_classifiedmake', to='classified_app.classifiedemake'),
        ),
    ]
