# Generated by Django 3.2.6 on 2022-09-03 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classified_app', '0017_auto_20220903_1133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classifiedcategory',
            name='image',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='classified_category_images'),
        ),
        migrations.AlterField(
            model_name='classifiedsubcategory',
            name='image',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='classified_subcategory_images'),
        ),
    ]
