# Generated by Django 3.2.6 on 2022-09-26 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classified_app', '0019_rename_category_classifiedemake_subcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='classified',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
