# Generated by Django 3.2.6 on 2022-09-29 06:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classified_app', '0021_auto_20220928_1051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classifiedmedia',
            name='classified',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='classifiedmedia_classified', to='classified_app.classified'),
        ),
    ]
