# Generated by Django 3.2.6 on 2022-10-04 08:10

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('youonline_social_app', '0047_auto_20220928_1319'),
        ('classified_app', '0022_alter_classifiedmedia_classified'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassifiedView',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('classified', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classifiedview_classified', to='classified_app.classified')),
                ('viewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classifiedview_viewer', to='youonline_social_app.profile')),
            ],
            options={
                'db_table': 'ClassifiedView',
            },
        ),
    ]
