# Generated by Django 3.2.6 on 2022-10-05 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classified_app', '0024_alter_classifiedview_viewer'),
    ]

    operations = [
        migrations.AddField(
            model_name='classifiedcategory',
            name='view_count',
            field=models.BigIntegerField(default=0),
        ),
    ]
