# Generated by Django 3.2.6 on 2022-10-05 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classified_app', '0025_classifiedcategory_view_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='classified',
            name='view_count',
            field=models.BigIntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='ClassifiedView',
        ),
    ]
