# Generated by Django 3.2.6 on 2022-01-10 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youonline_social_app', '0002_auto_20220108_1057'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='social_account',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='social_platform',
            field=models.CharField(blank=True, choices=[('Google', 'Google'), ('Facebook', 'Facebook'), ('Twitter', 'Twitter'), ('Apple', 'Apple')], max_length=32, null=True),
        ),
    ]
