# Generated by Django 3.2.6 on 2022-01-15 05:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('youonline_social_app', '0003_auto_20220110_1717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userplaceslived',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='userplaceslived_city', to='youonline_social_app.city'),
        ),
        migrations.AlterField(
            model_name='userplaceslived',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='userplaceslived_country', to='youonline_social_app.country'),
        ),
        migrations.AlterField(
            model_name='userplaceslived',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userplaceslived_profile', to='youonline_social_app.profile'),
        ),
        migrations.AlterField(
            model_name='userplaceslived',
            name='state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='userplaceslived_state', to='youonline_social_app.state'),
        ),
    ]
