# Generated by Django 3.2.6 on 2022-01-24 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youonline_social_app', '0005_auto_20220121_1251'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_approved',
            field=models.BooleanField(default=True),
        ),
    ]
