# Generated by Django 3.2.6 on 2022-01-25 05:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('youonline_social_app', '0006_post_is_approved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useralbum',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='useralbum_profile', to='youonline_social_app.profile'),
        ),
        migrations.AlterField(
            model_name='useralbummedia',
            name='album',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='useralbummedia_album', to='youonline_social_app.useralbum'),
        ),
        migrations.AlterField(
            model_name='useralbummedia',
            name='post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='useralbummedia_post', to='youonline_social_app.post'),
        ),
    ]
