# Generated by Django 3.2.6 on 2022-02-14 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youonline_social_app', '0009_auto_20220211_1458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postmedia',
            name='background_image',
            field=models.FileField(blank=True, null=True, upload_to='background_images/%Y/%m'),
        ),
        migrations.AlterField(
            model_name='postmedia',
            name='post_audio',
            field=models.FileField(blank=True, null=True, upload_to='post_audios/%Y/%m'),
        ),
        migrations.AlterField(
            model_name='postmedia',
            name='post_image',
            field=models.ImageField(blank=True, null=True, upload_to='post_images/%Y/%m'),
        ),
        migrations.AlterField(
            model_name='postmedia',
            name='post_video',
            field=models.FileField(blank=True, null=True, upload_to='post_videos/%Y/%m'),
        ),
        migrations.AlterField(
            model_name='postmedia',
            name='vid_thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='post_videos/%Y/%m'),
        ),
    ]
