# Generated by Django 3.2.6 on 2022-02-22 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youonline_social_app', '0011_notification_read_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='blog_post',
            field=models.BooleanField(default=False),
        ),
    ]
