# Generated by Django 3.2.6 on 2022-03-01 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youonline_social_app', '0012_post_blog_post'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profilestory',
            old_name='media',
            new_name='media_image',
        ),
        migrations.AddField(
            model_name='profilestory',
            name='angle',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='profilestory',
            name='media_video',
            field=models.FileField(blank=True, null=True, upload_to='UserStories/%Y/%m'),
        ),
        migrations.AddField(
            model_name='profilestory',
            name='x_axis',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='profilestory',
            name='y_axis',
            field=models.FloatField(default=0.0),
        ),
    ]
