# Generated by Django 3.2.6 on 2022-03-04 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youonline_social_app', '0012_auto_20220301_1044'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilestory',
            name='duration',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profilestory',
            name='video_thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='UserStories/%Y/%m'),
        ),
    ]
