# Generated by Django 3.2.6 on 2022-03-16 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youonline_social_app', '0015_auto_20220314_1658'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentmedia',
            name='video_compressed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='commentreplymedia',
            name='video_compressed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='postmedia',
            name='video_compressed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profilestory',
            name='video_compressed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='useralbummedia',
            name='video_compressed',
            field=models.BooleanField(default=False),
        ),
    ]
