# Generated by Django 3.2.6 on 2022-03-17 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youonline_social_app', '0016_auto_20220316_1236'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentmedia',
            name='bucket_uploaded',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='commentreplymedia',
            name='bucket_uploaded',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='coverpicture',
            name='bucket_uploaded',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='postmedia',
            name='bucket_uploaded',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profilepicture',
            name='bucket_uploaded',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profilestory',
            name='bucket_uploaded',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='useralbummedia',
            name='bucket_uploaded',
            field=models.BooleanField(default=False),
        ),
    ]
