# Generated by Django 3.2.6 on 2022-03-18 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youonline_social_app', '0017_auto_20220317_1550'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilestory',
            name='is_compressed',
            field=models.BooleanField(default=False),
        ),
    ]
