# Generated by Django 3.2.6 on 2022-03-22 09:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('youonline_social_app', '0019_auto_20220321_1216'),
    ]

    operations = [
        migrations.CreateModel(
            name='DegreeType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=512, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'Degree Type',
            },
        ),
        migrations.RemoveField(
            model_name='userhighschool',
            name='degree_type',
        ),
        migrations.AddField(
            model_name='userhighschool',
            name='degree_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='youonline_social_app.degreetype'),
        ),
    ]
