# Generated by Django 3.2.6 on 2022-03-25 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youonline_social_app', '0021_profile_is_blocked'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='job_post',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='job_project_post',
            field=models.BooleanField(default=False),
        ),
    ]
