# Generated by Django 3.2.6 on 2022-04-12 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youonline_social_app', '0022_auto_20220325_1501'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userhighschool',
            name='degree_type',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.DeleteModel(
            name='DegreeType',
        ),
    ]
