# Generated by Django 3.2.6 on 2022-04-15 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youonline_social_app', '0023_auto_20220412_1333'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprivacysettings',
            name='see_followers_privacy',
            field=models.CharField(choices=[('Public', 'Public'), ('OnlyMe', 'OnlyMe'), ('Friends', 'Friends')], default='Public', max_length=32),
        ),
    ]
