# Generated by Django 3.2.6 on 2022-04-19 08:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('youonline_social_app', '0024_userprivacysettings_see_followers_privacy'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='story',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notification_profilestory', to='youonline_social_app.profilestory'),
        ),
        migrations.AlterField(
            model_name='profilestory',
            name='post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='post_profilestory', to='youonline_social_app.post'),
        ),
        migrations.AlterField(
            model_name='profilestory',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_profilestory', to='youonline_social_app.profile'),
        ),
    ]
