# Generated by Django 3.2.6 on 2022-04-20 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youonline_social_app', '0025_auto_20220419_1307'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='remove_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
