# Generated by Django 3.2.6 on 2022-04-19 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youonline_social_app', '0025_profile_remove_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='business_directory_post',
            field=models.BooleanField(default=False),
        ),
    ]
