# Generated by Django 3.2.6 on 2022-05-12 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youonline_social_app', '0027_exceptionrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilestory',
            name='except_friends',
            field=models.ManyToManyField(blank=True, related_name='privacy_except_friends', to='youonline_social_app.Profile'),
        ),
    ]
