# Generated by Django 3.2.6 on 2022-05-19 05:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('youonline_social_app', '0029_taguser_is_mentioned'),
    ]

    operations = [
        migrations.AddField(
            model_name='taguser',
            name='reply_comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='taguser_comment_reply', to='youonline_social_app.commentreply'),
        ),
    ]
