# Generated by Django 3.2.6 on 2022-05-25 10:32

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('youonline_social_app', '0029_auto_20220525_1127'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserActivity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('activity', models.TextField(blank=True, null=True)),
                ('interest', models.TextField(blank=True, null=True)),
                ('favorite_music', models.TextField(blank=True, null=True)),
                ('favorite_movie', models.TextField(blank=True, null=True)),
                ('favorite_tv_show', models.TextField(blank=True, null=True)),
                ('favorite_book', models.TextField(blank=True, null=True)),
                ('favorite_game', models.TextField(blank=True, null=True)),
                ('favorite_quote', models.TextField(blank=True, null=True)),
                ('about_me', models.TextField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='useractivity_profile', to='youonline_social_app.profile')),
            ],
            options={
                'db_table': 'UserActivity',
            },
        ),
    ]
