# Generated by Django 3.2.6 on 2022-05-24 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youonline_social_app', '0030_taguser_reply_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='friendrequest',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
    ]
