# Generated by Django 3.2.6 on 2022-05-27 12:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('youonline_social_app', '0031_user_maiden_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useractivity',
            name='profile',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='useractivity_profile', to='youonline_social_app.profile'),
        ),
    ]
