# Generated by Django 3.2.6 on 2022-06-17 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youonline_social_app', '0035_auto_20220617_1618'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='blocked_user',
            field=models.ManyToManyField(blank=True, null=True, related_name='_youonline_social_app_profile_blocked_user_+', to='youonline_social_app.Profile'),
        ),
    ]
