# Generated by Django 3.2.6 on 2022-06-27 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('youonline_social_app', '0034_post_product_post'),
        ('youonline_social_app', '0037_auto_20220620_1241'),
    ]

    operations = [
    ]
