# Generated by Django 3.2.6 on 2022-07-19 11:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('youonline_social_app', '0039_language_rtl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userhighschool',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userhighschool_profile', to='youonline_social_app.profile'),
        ),
    ]
