# Generated by Django 3.2.6 on 2022-07-28 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youonline_social_app', '0040_alter_userhighschool_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='blog_author',
            field=models.BooleanField(default=False),
        ),
    ]
