# Generated by Django 3.2.6 on 2022-07-30 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youonline_social_app', '0041_profile_blog_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='group_logo',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='page_logo',
            field=models.BooleanField(default=False),
        ),
    ]
