# Generated by Django 3.2.6 on 2022-09-21 09:50

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('job_app', '0052_auto_20220921_1448'),
        ('automotive_app', '0023_auto_20220921_1448'),
        ('property_app', '0013_auto_20220921_1448'),
        ('youonline_social_app', '0042_auto_20220730_1256'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyMedia',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('logo', models.ImageField(max_length=256, null=True, upload_to='Company/Logo/%Y/%m')),
                ('is_deleted', models.BooleanField(default=False)),
                ('is_compressed', models.BooleanField(default=False)),
                ('bucket_uploaded', models.BooleanField(default=False)),
                ('is_automotive', models.BooleanField(default=False)),
                ('is_property', models.BooleanField(default=False)),
                ('is_job', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('automotive', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='automotive_app.automotive')),
                ('job', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='job_app.job')),
                ('profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='youonline_social_app.profile')),
                ('property', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='property_app.property')),
            ],
            options={
                'db_table': 'CompanyMedia',
            },
        ),
    ]
