# Generated by Django 3.2.6 on 2022-09-23 10:22

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('classified_app', '0019_rename_category_classifiedemake_subcategory'),
        ('property_app', '0013_auto_20220921_1448'),
        ('job_app', '0052_auto_20220921_1448'),
        ('automotive_app', '0023_auto_20220921_1448'),
        ('youonline_social_app', '0043_companymedia'),
    ]

    operations = [
        migrations.CreateModel(
            name='PackagePlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(blank=True, choices=[('Basic', 'Basic Plan'), ('Standard', 'Standard Plan'), ('Premium', 'Premium Plan')], max_length=512, null=True)),
                ('subject', models.TextField(blank=True, default='Make your ad featured', null=True)),
                ('description', models.TextField(blank=True, default='Customer support', null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('featured_week', models.CharField(blank=True, choices=[('1 Week', '1 Week'), ('2 Week', '2 Week'), ('3 Week', '3 Week')], max_length=512, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('currency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='job_app.currency')),
            ],
            options={
                'db_table': 'PackagePlan',
            },
        ),
        migrations.CreateModel(
            name='PackagePlaneDetail',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('packege_type', models.CharField(blank=True, choices=[('Classified', 'Classified'), ('Automotive', 'Automotive'), ('Property', 'Property'), ('Job', 'Job')], max_length=512, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('automotive', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='automotive_app.automotive')),
                ('classified', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='classified_app.classified')),
                ('job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='job_app.job')),
                ('plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='youonline_social_app.packageplan')),
                ('property', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='property_app.property')),
            ],
            options={
                'db_table': 'PackagePlaneDetail',
            },
        ),
    ]
