# Generated by Django 3.2.6 on 2022-09-28 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youonline_social_app', '0046_profile_dial_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='mobile_privacy',
            field=models.CharField(choices=[('Hide', 'Hide'), ('Show', 'Show')], default='Show', max_length=64),
        ),
        migrations.AddField(
            model_name='profile',
            name='recommended_privacy',
            field=models.CharField(choices=[('Hide', 'Hide'), ('Show', 'Show')], default='Show', max_length=64),
        ),
        migrations.AddField(
            model_name='profile',
            name='special_offer_privacy',
            field=models.CharField(choices=[('Hide', 'Hide'), ('Show', 'Show')], default='Show', max_length=64),
        ),
    ]
