# Generated by Django 3.2.6 on 2022-10-06 04:39

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('automotive_app', '0031_auto_20221005_1810'),
        ('job_app', '0068_auto_20221005_1810'),
        ('classified_app', '0026_auto_20221005_1810'),
        ('property_app', '0023_auto_20221005_1810'),
        ('youonline_social_app', '0048_moduleviewhistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='PopularCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('automotive_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='automotive_app.automotivecategory')),
                ('classified_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='classified_app.classifiedcategory')),
                ('job_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='job_app.jobcategory')),
                ('property_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='property_app.category')),
            ],
            options={
                'db_table': 'PopularCategory',
            },
        ),
        migrations.CreateModel(
            name='CategoryCount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('automotive_category_count', models.BigIntegerField(default=0)),
                ('property_category_count', models.BigIntegerField(default=0)),
                ('job_category_count', models.BigIntegerField(default=0)),
                ('classified_category_count', models.BigIntegerField(default=0)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='youonline_social_app.popularcategory')),
            ],
            options={
                'db_table': 'CategoryCount',
            },
        ),
    ]
