# Generated by Django 3.2.6 on 2022-10-06 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youonline_social_app', '0049_categorycount_popularcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='moduleviewhistory',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='moduleviewhistory',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
