# Generated by Django 3.2.6 on 2022-10-06 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('youonline_social_app', '0050_auto_20221006_1141'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='popularcategory',
            name='automotive_category',
        ),
        migrations.RemoveField(
            model_name='popularcategory',
            name='classified_category',
        ),
        migrations.RemoveField(
            model_name='popularcategory',
            name='job_category',
        ),
        migrations.RemoveField(
            model_name='popularcategory',
            name='property_category',
        ),
        migrations.DeleteModel(
            name='CategoryCount',
        ),
        migrations.DeleteModel(
            name='PopularCategory',
        ),
    ]
