# Generated by Django 3.2.6 on 2022-10-26 07:37

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('classified_app', '0028_classified_business_type'),
        ('property_app', '0024_auto_20221018_1312'),
        ('automotive_app', '0034_automotive_dial_code'),
        ('youonline_social_app', '0051_auto_20221006_1209'),
    ]

    operations = [
        migrations.CreateModel(
            name='DealData',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('discount_percentage', models.IntegerField(blank=True, null=True)),
                ('discounted_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('deal_automotive', models.BooleanField(default=False)),
                ('deal_property', models.BooleanField(default=False)),
                ('deal_classified', models.BooleanField(default=False)),
                ('is_expired', models.BooleanField(default=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('automotive', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='automotive_app.automotive')),
                ('classified', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='classified_app.classified')),
                ('property', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='property_app.property')),
            ],
            options={
                'db_table': 'DealData',
            },
        ),
    ]
