# Generated by Django 3.2.6 on 2021-12-29 23:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('property_app', '0001_initial'),
        ('job_app', '0002_initial'),
        ('youonline_social_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportproperty',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='youonline_social_app.profile'),
        ),
        migrations.AddField(
            model_name='reportproperty',
            name='property',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='property_app.property'),
        ),
        migrations.AddField(
            model_name='propertymedia',
            name='post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='propertymedia_post', to='youonline_social_app.post'),
        ),
        migrations.AddField(
            model_name='propertymedia',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='youonline_social_app.profile'),
        ),
        migrations.AddField(
            model_name='propertymedia',
            name='property',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='property_app.property'),
        ),
        migrations.AddField(
            model_name='property',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='property_app.category'),
        ),
        migrations.AddField(
            model_name='property',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='youonline_social_app.city'),
        ),
        migrations.AddField(
            model_name='property',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='job_app.company'),
        ),
        migrations.AddField(
            model_name='property',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='youonline_social_app.country'),
        ),
        migrations.AddField(
            model_name='property',
            name='currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='job_app.currency'),
        ),
        migrations.AddField(
            model_name='property',
            name='feature',
            field=models.ManyToManyField(blank=True, to='property_app.PropertyFeatures'),
        ),
        migrations.AddField(
            model_name='property',
            name='language',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='youonline_social_app.language'),
        ),
        migrations.AddField(
            model_name='property',
            name='post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='post_property', to='youonline_social_app.post'),
        ),
        migrations.AddField(
            model_name='property',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='youonline_social_app.profile'),
        ),
        migrations.AddField(
            model_name='property',
            name='state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='youonline_social_app.state'),
        ),
        migrations.AddField(
            model_name='property',
            name='sub_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='property_app.subcategory'),
        ),
        migrations.AddField(
            model_name='property',
            name='sub_sub_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='property_app.subsubcategory'),
        ),
        migrations.AddField(
            model_name='favouriteproperty',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='youonline_social_app.profile'),
        ),
        migrations.AddField(
            model_name='favouriteproperty',
            name='property',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='property_app.property'),
        ),
        migrations.AddField(
            model_name='contactproperty',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='youonline_social_app.profile'),
        ),
        migrations.AddField(
            model_name='contactproperty',
            name='property',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='property_app.property'),
        ),
    ]
