# Generated by Django 3.2.6 on 2022-01-08 07:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('youonline_social_app', '0002_auto_20220108_1057'),
        ('property_app', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favouriteproperty',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='favouriteproperty_profile', to='youonline_social_app.profile'),
        ),
        migrations.AlterField(
            model_name='favouriteproperty',
            name='property',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='favouriteproperty_property', to='property_app.property'),
        ),
    ]
