# Generated by Django 3.2.6 on 2022-01-14 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('youonline_social_app', '0003_auto_20220110_1717'),
        ('property_app', '0003_auto_20220108_1242'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='favouriteproperty',
            unique_together={('profile', 'property')},
        ),
    ]
