# Generated by Django 3.2.6 on 2022-02-10 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property_app', '0004_alter_favouriteproperty_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertymedia',
            name='is_compressed',
            field=models.BooleanField(default=False),
        ),
    ]
