# Generated by Django 3.2.6 on 2022-03-23 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property_app', '0007_propertymedia_bucket_uploaded'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertymedia',
            name='floor_image',
            field=models.ImageField(max_length=256, null=True, upload_to='property_floor_images/%Y/%m'),
        ),
        migrations.AlterField(
            model_name='propertymedia',
            name='property_image',
            field=models.ImageField(max_length=256, null=True, upload_to='property_images/%Y/%m'),
        ),
        migrations.AlterField(
            model_name='propertymedia',
            name='property_video',
            field=models.FileField(max_length=256, null=True, upload_to='property_videos/%Y/%m'),
        ),
        migrations.AlterField(
            model_name='propertymedia',
            name='property_video_thumbnail',
            field=models.FileField(max_length=256, null=True, upload_to='property_videos_thumbnail/%Y/%m'),
        ),
    ]
