# Generated by Django 3.2.6 on 2022-08-26 06:25

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('youonline_social_app', '0042_auto_20220730_1256'),
        ('property_app', '0008_auto_20220323_1502'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertySearchHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='propertysearchhistory_profile', to='youonline_social_app.profile')),
                ('property', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='propertysearchhistory_property', to='property_app.property')),
            ],
            options={
                'db_table': 'PropertySearchHistory',
            },
        ),
    ]
