# Generated by Django 3.2.6 on 2022-09-12 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property_app', '0009_propertysearchhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='area_unit',
            field=models.CharField(blank=True, choices=[('Kanal', 'Kanal'), ('Marla', 'Marla'), ('SquareFeet', 'Square Feet'), ('SquareMeter', 'Square Meter'), ('SquareYard', 'Square Yard')], max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='furnished',
            field=models.CharField(blank=True, choices=[('Furnished', 'Furnished'), ('Unfurnished', 'Unfurnished')], max_length=255, null=True),
        ),
    ]
