# Generated by Django 3.2.6 on 2022-09-14 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property_app', '0010_auto_20220912_1611'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='property_type',
            field=models.CharField(blank=True, choices=[('Rent', 'Rent'), ('Sale', 'Sale')], max_length=255, null=True),
        ),
    ]
