# Generated by Django 3.2.6 on 2022-09-28 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property_app', '0014_property_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertymedia',
            name='floor_image',
            field=models.ImageField(blank=True, max_length=256, null=True, upload_to='property_floor_images/%Y/%m'),
        ),
        migrations.AlterField(
            model_name='propertymedia',
            name='property_image',
            field=models.ImageField(blank=True, max_length=256, null=True, upload_to='property_images/%Y/%m'),
        ),
        migrations.AlterField(
            model_name='propertymedia',
            name='property_video',
            field=models.FileField(blank=True, max_length=256, null=True, upload_to='property_videos/%Y/%m'),
        ),
        migrations.AlterField(
            model_name='propertymedia',
            name='property_video_thumbnail',
            field=models.FileField(blank=True, max_length=256, null=True, upload_to='property_videos_thumbnail/%Y/%m'),
        ),
    ]
