# Generated by Django 3.2.6 on 2022-09-28 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property_app', '0015_auto_20220928_1209'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='is_deal',
            field=models.BooleanField(default=False),
        ),
    ]
