# Generated by Django 3.2.6 on 2022-09-30 07:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('job_app', '0056_auto_20220930_1259'),
        ('property_app', '0016_property_is_deal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='property_company', to='job_app.company'),
        ),
    ]
