# Generated by Django 3.2.6 on 2022-10-03 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property_app', '0017_alter_property_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='dial_code',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
