# Generated by Django 3.2.6 on 2022-10-04 08:10

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('youonline_social_app', '0047_auto_20220928_1319'),
        ('property_app', '0019_alter_property_bedrooms'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyView',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='propertyview_property', to='property_app.property')),
                ('viewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='propertyview_viewer', to='youonline_social_app.profile')),
            ],
            options={
                'db_table': 'PropertyView',
            },
        ),
    ]
