# Generated by Django 3.2.6 on 2022-10-05 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property_app', '0022_category_view_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='view_count',
            field=models.BigIntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='PropertyView',
        ),
    ]
