# Generated by Django 3.2.6 on 2022-11-15 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property_app', '0024_auto_20221018_1312'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='category/images'),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='subcategory/images'),
        ),
        migrations.AddField(
            model_name='subsubcategory',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='subsubcategory/images'),
        ),
    ]
