# Generated by Django 3.2.6 on 2022-01-06 12:57

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('youonline_social_app', '0001_initial'),
        ('video_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videoplaylistpost',
            name='playlist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='videoplaylistpost_playlist', to='video_app.videoplaylist'),
        ),
        migrations.AlterField(
            model_name='videoplaylistpost',
            name='post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='videoplaylistpost_post', to='youonline_social_app.post'),
        ),
        migrations.CreateModel(
            name='VideoSubscribe',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('channel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='videosubscribe_channel', to='video_app.videochannel')),
                ('profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='videosubscribe_profile', to='youonline_social_app.profile')),
            ],
            options={
                'db_table': 'VideoSubscribe',
                'unique_together': {('profile', 'channel')},
            },
        ),
    ]
