# Generated by Django 3.2.6 on 2022-01-10 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_app', '0003_auto_20220107_1457'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='duration',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
