# Generated by Django 3.2.6 on 2022-03-18 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_app', '0006_auto_20220211_1458'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='bucket_uploaded',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='video',
            name='video_compressed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='video',
            name='vid_thumbnail',
            field=models.FileField(blank=True, max_length=256, null=True, upload_to='videos_module/%Y/%m'),
        ),
        migrations.AlterField(
            model_name='video',
            name='video',
            field=models.FileField(blank=True, max_length=256, null=True, upload_to='videos_module/%Y/%m'),
        ),
    ]
