# Generated by Django 3.2.6 on 2022-03-21 04:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('video_app', '0008_auto_20220318_1527'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videochannel',
            name='cover',
        ),
        migrations.RemoveField(
            model_name='videochannel',
            name='picture',
        ),
    ]
