# Generated by Django 3.2.6 on 2022-07-04 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_app', '0010_auto_20220329_1313'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='inactive_video',
            field=models.BooleanField(default=False),
        ),
    ]
