# Generated by Django 3.2.6 on 2022-01-24 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community_app', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='approval_required',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='group',
            name='who_can_post',
            field=models.CharField(blank=True, choices=[('adminonly', 'adminonly'), ('members', 'members')], default='members', max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='group',
            name='privacy',
            field=models.CharField(choices=[('Public', 'Public'), ('OnlyMe', 'OnlyMe'), ('Friends', 'Friends')], default='Public', max_length=255),
        ),
        migrations.AlterField(
            model_name='page',
            name='privacy',
            field=models.CharField(choices=[('Public', 'Public'), ('OnlyMe', 'OnlyMe'), ('Friends', 'Friends')], default='Public', max_length=255),
        ),
    ]
