# Generated by Django 3.2.6 on 2022-02-11 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community_app', '0003_auto_20220124_1117'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupbanner',
            name='is_compressed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pagebanner',
            name='is_compressed',
            field=models.BooleanField(default=False),
        ),
    ]
