# Generated by Django 3.2.6 on 2022-02-14 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community_app', '0004_auto_20220211_1458'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='is_promoted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='page',
            name='is_promoted',
            field=models.BooleanField(default=False),
        ),
    ]
