# Generated by Django 3.2.6 on 2022-04-27 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community_app', '0006_auto_20220318_1123'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='username',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
