# Generated by Django 3.2.6 on 2022-05-23 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community_app', '0007_page_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagefollower',
            name='is_administrator',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pagefollower',
            name='is_editor',
            field=models.BooleanField(default=False),
        ),
    ]
