# Generated by Django 3.2.6 on 2022-06-13 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community_app', '0008_auto_20220523_1013'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='business_page',
            field=models.BooleanField(default=False),
        ),
    ]
