# Generated by Django 3.2.6 on 2022-02-25 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='is_compressed',
            field=models.BooleanField(default=False),
        ),
    ]
