# Generated by Django 3.2.6 on 2022-03-10 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0002_blog_is_compressed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='featured_image',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='Blogs/%Y/%m'),
        ),
    ]
