# Generated by Django 3.2.6 on 2022-03-21 04:44

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0003_alter_blog_featured_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='featured_image',
        ),
        migrations.CreateModel(
            name='BlogMedia',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('featured_image', models.ImageField(blank=True, max_length=255, null=True, upload_to='Blogs/%Y/%m')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('is_compressed', models.BooleanField(default=False)),
                ('bucket_uploaded', models.BooleanField(default=False)),
                ('blog', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='blogmedia_blog', to='blog_app.blog')),
            ],
            options={
                'db_table': 'BlogMedia',
            },
        ),
    ]
