# Generated by Django 3.2.6 on 2022-07-01 07:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('youonline_social_app', '0039_language_rtl'),
        ('blog_app', '0005_alter_blog_view_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='language',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='youonline_social_app.language'),
        ),
    ]
