# Generated by Django 3.2.6 on 2022-01-05 04:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('youonline_social_app', '0001_initial'),
        ('job_app', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='currency',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='currency_country', to='youonline_social_app.country'),
        ),
    ]
