# Generated by Django 3.2.6 on 2022-02-24 06:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('job_app', '0003_currency_country'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'Job Category',
            },
        ),
        migrations.RemoveField(
            model_name='job',
            name='duration_months',
        ),
        migrations.RemoveField(
            model_name='job',
            name='duration_years',
        ),
        migrations.AddField(
            model_name='job',
            name='duration',
            field=models.CharField(blank=True, choices=[('7 days', '7 days'), ('14 days', '14 days'), ('30 days', '30 days')], max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='experience',
            field=models.CharField(blank=True, choices=[('Less 1 year', 'Less 1 year'), ('More than 1 year', 'More than 1 year'), ('2-5', '2-4'), ('5-7', '5-7')], max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='job_type',
            field=models.CharField(blank=True, choices=[('Web developer', 'Web developer'), ('Web designer', 'Web designer'), ('Project manager', 'Project manager')], max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='location',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='employment_type',
            field=models.CharField(blank=True, choices=[('Fresh', 'Fresh'), ('Intermediate', 'Intermediate'), ('Senior', 'Senior')], max_length=30, null=True),
        ),
        migrations.AlterModelTable(
            name='company',
            table='Company',
        ),
        migrations.AlterModelTable(
            name='currency',
            table='Currency',
        ),
        migrations.AlterModelTable(
            name='favoritejob',
            table='Favorite Job',
        ),
        migrations.AlterModelTable(
            name='industry',
            table='Industry',
        ),
        migrations.AlterModelTable(
            name='job',
            table='Job',
        ),
        migrations.AddField(
            model_name='job',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='job_app.jobcategory'),
        ),
    ]
