# Generated by Django 3.2.6 on 2022-02-24 07:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('job_app', '0006_auto_20220224_1143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='skill',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='job_skill', to='job_app.skill'),
        ),
    ]
