# Generated by Django 3.2.6 on 2022-02-25 05:48

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('youonline_social_app', '0012_post_blog_post'),
        ('job_app', '0008_job_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobApply',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('cv', models.FileField(blank=True, null=True, upload_to='Apply/CV/%Y/%m')),
                ('maximum_experience', models.IntegerField(blank=True, null=True)),
                ('expected_salary', models.IntegerField(blank=True, null=True)),
                ('job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jobapply_job', to='job_app.job')),
                ('profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='youonline_social_app.profile')),
            ],
            options={
                'db_table': 'Apply',
            },
        ),
    ]
