# Generated by Django 3.2.6 on 2022-02-25 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job_app', '0009_jobapply'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='jobapply',
            table='JobApply',
        ),
    ]
