# Generated by Django 3.2.6 on 2022-02-25 09:54

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('youonline_social_app', '0012_post_blog_post'),
        ('job_app', '0010_alter_jobapply_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job_Profile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='Job Profile/image/%Y/%m')),
                ('headline', models.CharField(blank=True, max_length=35, null=True)),
                ('first_name', models.CharField(blank=True, max_length=255, null=True)),
                ('last_name', models.CharField(blank=True, max_length=255, null=True)),
                ('about', models.TextField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('profile', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='youonline_social_app.profile')),
                ('skill', models.ManyToManyField(blank=True, null=True, to='job_app.Skill')),
            ],
            options={
                'db_table': 'Job Profile',
            },
        ),
    ]
