# Generated by Django 3.2.6 on 2022-02-25 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('youonline_social_app', '0012_post_blog_post'),
        ('job_app', '0011_job_profile'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Job_Profile',
            new_name='JobProfile',
        ),
    ]
