# Generated by Django 3.2.6 on 2022-02-28 06:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('job_app', '0012_rename_job_profile_jobprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='jobprofile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='job_app.jobprofile'),
        ),
        migrations.AddField(
            model_name='jobprofile',
            name='description',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='jobprofile',
            name='headline',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
