# Generated by Django 3.2.6 on 2022-02-28 07:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('job_app', '0014_jobproject'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobproject',
            name='profile',
        ),
        migrations.AddField(
            model_name='jobproject',
            name='jobprofile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='job_app.jobprofile'),
        ),
    ]
