# Generated by Django 3.2.6 on 2022-03-04 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job_app', '0018_auto_20220302_1615'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='category',
        ),
        migrations.DeleteModel(
            name='JobCategory',
        ),
    ]
