# Generated by Django 3.2.6 on 2022-03-15 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_app', '0019_auto_20220304_1450'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='duration',
        ),
        migrations.AlterField(
            model_name='job',
            name='experience',
            field=models.CharField(blank=True, choices=[('Less than one year', 'Less than one year'), ('More than one year', 'More than one year'), ('Two year', 'Two year'), ('Three year', 'Three year')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='job_type',
            field=models.CharField(blank=True, choices=[('Remote', 'Remote'), ('Part Time', 'Part Time'), ('Full Time', 'Full Time'), ('Contract Base', 'Contract Base')], max_length=255, null=True),
        ),
    ]
