# Generated by Django 3.2.6 on 2022-03-16 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_app', '0023_job_mobile'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobprofile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
