# Generated by Django 3.2.6 on 2022-03-17 07:17

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('youonline_social_app', '0016_auto_20220316_1236'),
        ('job_app', '0024_jobprofile_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobapply',
            name='expected_salary',
        ),
        migrations.RemoveField(
            model_name='jobapply',
            name='maximum_experience',
        ),
        migrations.RemoveField(
            model_name='jobapply',
            name='profile',
        ),
        migrations.AddField(
            model_name='jobapply',
            name='email',
            field=models.EmailField(blank=True, max_length=60, null=True, verbose_name='email'),
        ),
        migrations.AddField(
            model_name='jobapply',
            name='full_name',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='jobapply',
            name='jobprofile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='job_app.jobprofile'),
        ),
        migrations.AddField(
            model_name='jobapply',
            name='mobile',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.CreateModel(
            name='JobStory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('text', models.CharField(blank=True, max_length=255, null=True)),
                ('font_family', models.CharField(blank=True, max_length=128, null=True)),
                ('background_color', models.CharField(blank=True, max_length=128, null=True)),
                ('text_color', models.CharField(blank=True, max_length=128, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='UserStories/%Y/%m')),
                ('video', models.FileField(blank=True, null=True, upload_to='UserStories/%Y/%m')),
                ('video_thumbnail', models.ImageField(blank=True, null=True, upload_to='UserStories/%Y/%m')),
                ('duration', models.IntegerField(blank=True, null=True)),
                ('x_axis', models.FloatField(default=0.0)),
                ('y_axis', models.FloatField(default=0.0)),
                ('angle', models.FloatField(default=0.0)),
                ('story_type', models.CharField(choices=[('Text', 'Text'), ('Media', 'Media')], default='Text', max_length=32)),
                ('privacy', models.CharField(choices=[('Public', 'Public'), ('OnlyMe', 'OnlyMe'), ('Friends', 'Friends')], default='Public', max_length=32)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('video_compressed', models.BooleanField(default=False)),
                ('jobprofile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job_app.jobprofile')),
                ('post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='youonline_social_app.post')),
            ],
            options={
                'db_table': 'JobStory',
            },
        ),
    ]
