# Generated by Django 3.2.6 on 2022-03-17 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_app', '0025_auto_20220317_1217'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapply',
            name='education',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
