# Generated by Django 3.2.6 on 2022-03-17 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_app', '0026_jobapply_education'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobproject',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='JobProject/images/%Y/%m'),
        ),
        migrations.AddField(
            model_name='jobproject',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='JobProject/videos/%Y/%m'),
        ),
        migrations.AlterField(
            model_name='jobstory',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='JobStories/images/%Y/%m'),
        ),
        migrations.AlterField(
            model_name='jobstory',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='JobStories/videos/%Y/%m'),
        ),
        migrations.AlterField(
            model_name='jobstory',
            name='video_thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='JobStories/%Y/%m'),
        ),
    ]
