# Generated by Django 3.2.6 on 2022-03-17 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_app', '0027_auto_20220317_1457'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='job_duration',
            field=models.CharField(blank=True, choices=[('7 days', '7 days'), ('15 days', '15 days'), ('None', 'None')], max_length=30, null=True),
        ),
    ]
