# Generated by Django 3.2.6 on 2022-03-18 10:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('job_app', '0032_jobsearchhistory_jobprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobsearchhistory',
            name='job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='job_app.job'),
        ),
    ]
