# Generated by Django 3.2.6 on 2022-03-23 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_app', '0035_auto_20220322_1004'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobprojectmedia',
            name='bucket_uploaded',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterModelTable(
            name='favoritejob',
            table='FavoriteJob',
        ),
        migrations.AlterModelTable(
            name='jobalert',
            table='JobAlert',
        ),
        migrations.AlterModelTable(
            name='jobendoresements',
            table='JobEndoresements',
        ),
        migrations.AlterModelTable(
            name='jobprofile',
            table='JobProfile',
        ),
        migrations.AlterModelTable(
            name='jobproject',
            table='JobProject',
        ),
        migrations.AlterModelTable(
            name='jobprojectmedia',
            table='JobProjectMedia',
        ),
        migrations.AlterModelTable(
            name='jobsearchhistory',
            table='JobSearchHistory',
        ),
    ]
