# Generated by Django 3.2.6 on 2022-03-25 10:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('youonline_social_app', '0022_auto_20220325_1501'),
        ('job_app', '0036_auto_20220323_1657'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobproject',
            name='post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='youonline_social_app.post'),
        ),
    ]
