# Generated by Django 3.2.6 on 2022-03-29 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_app', '0037_jobproject_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobstory',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
