# Generated by Django 3.2.6 on 2022-03-30 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_app', '0039_auto_20220330_1006'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobstory',
            name='bucket_uploaded',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='jobstory',
            name='is_compressed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterUniqueTogether(
            name='jobapply',
            unique_together={('jobprofile', 'job')},
        ),
    ]
