# Generated by Django 3.2.6 on 2022-03-30 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_app', '0040_auto_20220330_1257'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobprofile',
            name='backgroud_image',
        ),
        migrations.AddField(
            model_name='jobprofile',
            name='background_image',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='JobProfile/image/%Y/%m'),
        ),
        migrations.AddField(
            model_name='jobprofile',
            name='bucket_uploaded',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='jobprofile',
            name='image',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='JobProfile/image/%Y/%m'),
        ),
    ]
