# Generated by Django 3.2.6 on 2022-04-04 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_app', '0042_auto_20220331_1026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobprojectmedia',
            name='vid_thumbnail',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to='JobProject/thumbnail/%Y/%m'),
        ),
    ]
