# Generated by Django 3.2.6 on 2022-08-27 06:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('youonline_social_app', '0042_auto_20220730_1256'),
        ('job_app', '0044_jobapply_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jobs_post', to='youonline_social_app.post'),
        ),
    ]
