# Generated by Django 3.2.6 on 2022-09-02 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_app', '0046_auto_20220829_1040'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobcategory',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='category/images'),
        ),
    ]
