# Generated by Django 3.2.6 on 2022-09-06 12:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('job_app', '0047_jobcategory_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobsearchhistory',
            name='job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jobsearchhistory_job', to='job_app.job'),
        ),
    ]
