# Generated by Django 3.2.6 on 2022-09-13 10:31

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('youonline_social_app', '0042_auto_20220730_1256'),
        ('job_app', '0048_alter_jobsearchhistory_job'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='position_type',
            field=models.CharField(blank=True, choices=[('Hourly', 'Hourly'), ('Weekly', 'Weekly'), ('Monthly', 'Monthly'), ('Yearly', 'Yearly')], max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='job_profile', to='youonline_social_app.profile'),
        ),
        migrations.AddField(
            model_name='job',
            name='salary_end',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='salary_period',
            field=models.CharField(blank=True, choices=[('Hourly', 'Hourly'), ('Weekly', 'Weekly'), ('Monthly', 'Monthly'), ('Yearly', 'Yearly')], max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='salary_start',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='verification_status',
            field=models.CharField(blank=True, choices=[('Pending', 'Pending'), ('Verified', 'Verified'), ('Rejected', 'Rejected')], default='Pending', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='contact_person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='job_contact_person', to='youonline_social_app.profile'),
        ),
        migrations.AlterField(
            model_name='job',
            name='job_type',
            field=models.CharField(blank=True, choices=[('Part Time', 'Part Time'), ('Full Time', 'Full Time'), ('Contract Base', 'Contract Base'), ('Remote', 'Remote'), ('InOffice', 'In-Office'), ('Hybrid', 'Hybrid')], max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='JobMedia',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('job_image', models.ImageField(max_length=256, null=True, upload_to='Job_images/%Y/%m')),
                ('job_video', models.FileField(max_length=256, null=True, upload_to='Job_video/%Y/%m')),
                ('vid_thumbnail', models.FileField(max_length=256, null=True, upload_to='Job_video/%Y/%m')),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('is_compressed', models.BooleanField(default=False)),
                ('video_compressed', models.BooleanField(default=False)),
                ('bucket_uploaded', models.BooleanField(default=False)),
                ('job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jobmedia_job', to='job_app.job')),
                ('post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jobmedia_post', to='youonline_social_app.post')),
                ('profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jobmedia_profile', to='youonline_social_app.profile')),
            ],
            options={
                'db_table': 'JobMedia',
            },
        ),
    ]
