# Generated by Django 3.2.6 on 2022-09-15 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_app', '0050_alter_job_position_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='job_type',
            field=models.CharField(blank=True, choices=[('Part Time', 'Part Time'), ('Full Time', 'Full Time'), ('Contract', 'Contract'), ('Remote', 'Remote'), ('In-Office', 'In-Office'), ('Hybrid', 'Hybrid')], max_length=255, null=True),
        ),
    ]
