# Generated by Django 3.2.6 on 2022-09-29 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_app', '0054_alter_favoritejob_job'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='is_promoted',
            field=models.BooleanField(default=False),
        ),
    ]
