# Generated by Django 3.2.6 on 2022-09-30 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job_app', '0058_company_dial_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='compnay_category',
            new_name='company_category',
        ),
    ]
