# Generated by Django 3.2.6 on 2022-10-04 08:10

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('youonline_social_app', '0047_auto_20220928_1319'),
        ('job_app', '0059_rename_compnay_category_company_company_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobView',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobview_job', to='job_app.job')),
                ('viewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobview_viewer', to='youonline_social_app.profile')),
            ],
            options={
                'db_table': 'JobView',
            },
        ),
    ]
