# Generated by Django 3.2.6 on 2022-10-04 10:34

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('youonline_social_app', '0047_auto_20220928_1319'),
        ('job_app', '0061_alter_jobview_viewer'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapply',
            name='cover_letter',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobapply',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jobapply_profile', to='youonline_social_app.profile'),
        ),
        migrations.AlterUniqueTogether(
            name='jobapply',
            unique_together={('profile', 'job')},
        ),
        migrations.CreateModel(
            name='JobApplyMedia',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('resume_file', models.FileField(blank=True, null=True, upload_to='Apply_Jobs/Resume/%Y/%m')),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('is_compressed', models.BooleanField(default=False)),
                ('bucket_uploaded', models.BooleanField(default=False)),
                ('apply', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jobapplymedia_apply', to='job_app.jobapply')),
            ],
            options={
                'db_table': 'JobApplyMedia',
            },
        ),
        migrations.RemoveField(
            model_name='jobapply',
            name='cv',
        ),
        migrations.RemoveField(
            model_name='jobapply',
            name='jobprofile',
        ),
    ]
