# Generated by Django 3.2.6 on 2022-10-04 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job_app', '0062_auto_20221004_1534'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='jobapplymedia',
            table=None,
        ),
    ]
