# Generated by Django 3.2.6 on 2022-10-04 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job_app', '0063_alter_jobapplymedia_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='jobapplymedia',
            table='JobApplyMedia',
        ),
    ]
