# Generated by Django 3.2.6 on 2022-10-04 12:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('youonline_social_app', '0047_auto_20220928_1319'),
        ('job_app', '0064_alter_jobapplymedia_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplymedia',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jobapplymedia_profile', to='youonline_social_app.profile'),
        ),
    ]
