# Generated by Django 3.2.6 on 2022-10-05 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_app', '0066_jobsearchhistory_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobcategory',
            name='view_count',
            field=models.BigIntegerField(default=0),
        ),
    ]
