# Generated by Django 3.2.6 on 2022-10-07 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_app', '0069_currency_currency_symbol'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='company_status',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='company',
            name='company_type',
            field=models.CharField(blank=True, choices=[('Classified', 'Classified'), ('Automotive', 'Automotive'), ('Job', 'Job'), ('Property', 'Property')], max_length=200, null=True),
        ),
    ]
