# Generated by Django 3.2.6 on 2022-10-13 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_app', '0070_auto_20221007_1655'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='dial_code',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
