# Generated by Django 3.2.6 on 2022-10-20 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_app', '0071_job_dial_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplymedia',
            name='resume_extension',
            field=models.CharField(blank=True, max_length=55, null=True),
        ),
        migrations.AddField(
            model_name='jobapplymedia',
            name='resume_name',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
