# Generated by Django 3.2.6 on 2022-10-20 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_app', '0072_auto_20221020_1154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobcategory',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='category/images'),
        ),
    ]
