# Generated by Django 3.2.6 on 2022-10-21 04:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('job_app', '0073_alter_jobcategory_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobapplymedia',
            name='apply',
        ),
        migrations.AddField(
            model_name='jobapply',
            name='resume',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jobapply_job', to='job_app.jobapplymedia'),
        ),
    ]
