# Generated by Django 3.2.6 on 2022-10-21 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_app', '0074_auto_20221021_0934'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapply',
            name='dial_code',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
