# Generated by Django 3.2.6 on 2022-10-27 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_app', '0076_alter_job_position_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='lat',
            field=models.DecimalField(blank=True, decimal_places=16, max_digits=30, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='long',
            field=models.DecimalField(blank=True, decimal_places=16, max_digits=30, null=True),
        ),
    ]
