# Generated by Django 3.2.6 on 2022-11-01 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_app', '0077_auto_20221027_1116'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplymedia',
            name='file_size',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
